- name: install nginx
  apt: pkg=nginx state=installed

- name: configure nginx sites as available
  template: src={{item}} dest=/etc/nginx/sites-available/{{ item | basename }}
  with_fileglob:
   - templates/vhosts/*

- name: Configure nginx sites as enabled
  file: path=/etc/nginx/sites-enabled/{{ item | basename }} src=../sites-available/{{ item | basename }} state=link
  with_fileglob:
   - templates/vhosts/*

