---
# - name: Install Boto
#   ansible.builtin.pip:
#     state: present
#     name:
#       - boto
#       - botocore
#   tags:
#     - aws
# - name: Install Boto
#   ansible.builtin.apt:
#     state: present
#     name:
#       - python3-boto3
#       - python3-botocore
#   become: true
#   become_method: sudo
#   tags:
#     - aws

- name: Aquarionics DNS
  ansible.builtin.import_tasks: zones_aqcom/aquarionics.yml

- name: Socksandpuppets DNS - Cloudflare
  ansible.builtin.include_tasks: zones_aqcom/socksandpuppets.yml
  tags:
    - cloudflare
    - socksandpuppets

- name: Update Route53 for aqxs
  ansible.builtin.include_tasks: zones_aqcom/aqxs.yml
  tags:
    - aws

- name: Update Route53 for camlarp
  ansible.builtin.include_tasks: zones_aqcom/camlarp.yml
  tags:
    - aws
    - camlarp

- name: Update Route53 for cleartext
  ansible.builtin.include_tasks: zones_aqcom/cleartext.yml
  tags:
    - aws

- name: Update Route53 for factionfiction
  ansible.builtin.include_tasks: zones_aqcom/factionfiction.yml
  tags:
    - aws

- name: Update Route53 for warehouse
  ansible.builtin.include_tasks: zones_aqcom/warehouse.yml
  tags:
    - aws

- name: Update Route53 for monthlymoon
  ansible.builtin.include_tasks: zones_aqcom/monthlymoon.yml
  tags:
    - aws
    - monthlymoon

- name: Update Route53 for ludoistic
  ansible.builtin.include_tasks: zones_istic/ludoistic.yml
  tags:
    - aws
    - ludoistic

- name: Update Route53 for carcosadreams
  ansible.builtin.include_tasks: zones_istic/carcosadreams.yml
  tags:
    - aws
    - carcosadreams

- name: Update Route53 for larpfic
  ansible.builtin.include_tasks: zones_aqcom/larpfic.yml
  tags:
    - aws
    - larpfic

- name: Update Route53 for larpme
  ansible.builtin.include_tasks: zones_aqcom/larpme.yml
  tags:
    - aws
    - larpme
    - larpmeuk

- name: Update Route53 for conterio
  ansible.builtin.include_tasks: zones_aqcom/conterio.yml
  tags:
    - aws
    - conterio

- name: Update Route53 for kastark
  ansible.builtin.include_tasks: zones_aqcom/kastark.yml
  tags:
    - aws
    - kastark

- name: Update Route53 for hubris
  ansible.builtin.include_tasks: zones_aqcom/hubris.yml
  tags:
    - aws
    - hubris

- name: Update Route53 for bromioscreations
  ansible.builtin.include_tasks: zones_aqcom/bromioscreations.yml
  tags:
    - aws
    - bromioscreations

- name: Update Route53 for istic
  ansible.builtin.include_tasks: zones_istic/istic.yml
  tags:
    - aws
    - istic_net
    - istic_sys
    - sftp

- name: Update Route53 for nanocountdown
  ansible.builtin.include_tasks: zones_istic/nanocountdown.yml
  tags:
    - aws
    - nanocountdown

- name: Novelathon DNS
  ansible.builtin.import_tasks: zones_istic/novelathon.yml

- name: Update Route53 for dagon_church
  ansible.builtin.include_tasks: zones_istic/dagon_church.yml
  tags:
    - aws
    - dagon_church

- name: Update Route53 for nicholasavenell
  ansible.builtin.include_tasks: zones_aqcom/nicholasavenell.yml
  tags:
    - aws
    - nicholasavenell

- name: Update Route53 for bloomfeedapp
  ansible.builtin.include_tasks: zones_aqcom/bloomfeedapp.yml
  tags:
    - aws
    - bloomfeedapp

- name: Update Route53 for deathuntodarkness
  ansible.builtin.include_tasks: zones_aqcom/deathuntodarkness.yml
  tags:
    - aws
    - deathuntodarkness

- name: Update Route53 for bromios
  ansible.builtin.include_tasks: zones_aqcom/bromios.yml
  tags:
    - aws
    - bromios

- name: Cernunnosdionysus DNS
  ansible.builtin.include_tasks: zones_istic/cernunnosdionysus.yml
  tags:
    - aws
    - cernunnosdionysus

- name: Update Route53 for istic_dev
  ansible.builtin.include_tasks: zones_istic/istic_dev.yml
  tags:
    - aws
    - istic_dev
