
# Based on https://github.com/cmprescott/ansible-role-filebot

- name: "Setup |  deb | check for installation"
  stat: path="{{ filebot_deb_bin }}"
  register: filebot_bin

- name: "Setup |  deb | download installer"
  get_url: url="{{ filebot_deb_url }}" dest="{{ filebot_deb_tmp }}"
  when: not filebot_bin.stat.exists

- name: "Setup |  deb | run the installer"
  become: Yes
  apt: deb="{{ filebot_deb_tmp }}"
  when: not filebot_bin.stat.exists

