---
- name: Install CUPS
  ansible.builtin.apt:
    pkg: cups
    state: present

- name: Add listen port to cups
  ansible.builtin.lineinfile:
    state: present
    path: /etc/cups/cupsd.conf
    line: "Listen 0.0.0.0:631 "
    insertafter: ^Listen
  notify:
    - restart cups

- name: Add access network to access
  ansible.builtin.lineinfile:
    state: present
    path: /etc/cups/cupsd.conf
    line: "  Allow 192.168.0.0/16"
    insertafter: ^<Location />
  notify:
    - restart cups

- name: Add access network to admin
  ansible.builtin.lineinfile:
    state: present
    path: /etc/cups/cupsd.conf
    line: "  Allow 192.168.0.0/16"
    insertafter: ^<Location /admin>
  notify:
    - restart cups

- name: Remove localhost limit
  ansible.builtin.lineinfile:
    state: absent
    path: /etc/cups/cupsd.conf
    line: Listen localhost:631
  notify:
    - restart cups

- name: Add Aquarion to lpadmin
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: aquarion
    groups: lpadmin
    append: true
  notify:
    - restart cups

- name: Get Thermal Print drivers
  ansible.builtin.git:
    repo: https://github.com/klirichek/zj-58.git
    dest: /usr/src/zj-58
    version: master
  register: driverupdate

- name: Remove old driver build file
  ansible.builtin.file:
    state: absent
    path: /usr/src/zj-58/build
  when: driverupdate.changed

- name: Remove old print driver
  ansible.builtin.file:
    state: absent
    path: /usr/share/cups/model/zjiang
  when: driverupdate.changed

- name: Install dev files for cups
  ansible.builtin.apt:
    pkg:
      - build-essential
      - cmake
      - libcups2-dev
      - libcupsimage2-dev
    state: present

- name: Add a build directory
  ansible.builtin.file:
    path: /usr/src/zj-58/build
    mode: 0755
    state: directory

- name: Prepare Thermal Printer Drivers build environment
  ansible.builtin.shell: |
    cmake /usr/src/zj-58
  args:
    chdir: /usr/src/zj-58/build
    creates: /usr/src/zj-58/build/cmake_install.cmake

- name: Build Thermal Printer Drivers
  ansible.builtin.shell: |
    cmake --build .
  args:
    chdir: /usr/src/zj-58/build
    creates: /usr/src/zj-58/build/ppd/zj58.ppd

- name: Thermal Printer Drivers installation
  ansible.builtin.shell: |
    make install
  args:
    chdir: /usr/src/zj-58/build
    creates: /usr/share/cups/model/zjiang

- name: Set up HPLIP temp directory
  ansible.builtin.file:
    path: /usr/src/hplip
    state: directory
    mode: 0755

# ### <HP41>From https://github.com/HP41/ansible-cups
- name: Install Expect
  ansible.builtin.apt:
    name: expect
    state: present

- name: Install HPLIP
  ansible.builtin.apt:
    name: hplip
    state: present
  register: hplip_package

- name: Copy hp-plugin-install.exp install script to /usr/src/hplip/
  ansible.builtin.copy:
    src: files/hp-plugin-install.exp
    dest: /usr/src/hplip/hp-plugin-install.exp
    mode: a+rx
  register: hplip

- name: Installing HP Plugin using an except script to avoid user interaction
  ansible.builtin.command: /usr/src/hplip/hp-plugin-install.exp
  when: hplip.changed or hplip_package.changed
# ### </HP41>

- name: Test printer config
  ansible.builtin.copy:
    src: printers.conf
    dest: /etc/cups/printers.conf
    owner: root
    group: lp
    mode: 0664
  check_mode: true
  register: test_config

- name: Test thermal printer ppd
  ansible.builtin.copy:
    src: /usr/share/cups/model/zjiang/zj58.ppd
    dest: /etc/cups/ppd/Receipt.ppd
    owner: root
    group: lp
    mode: 0664
    remote_src: true
  check_mode: true
  register: test_receipt

- name: Test laserjet printer ppd
  ansible.builtin.copy:
    src: LaserJet.ppd
    dest: /etc/cups/LaserJet.ppd
    owner: root
    group: lp
    mode: 0664
  check_mode: true
  register: test_laserjet

- name: Stop CUPS
  ansible.builtin.service:
    name: cups
    state: stopped
  when: test_config.changed or test_receipt.changed or test_laserjet.changed

- name: Apply printer config
  ansible.builtin.copy:
    src: printers.conf
    dest: /etc/cups/printers.conf
    backup: true
    owner: root
    group: lp
    mode: 0664
  notify:
    - restart cups

- name: Apply thermal printer ppd
  ansible.builtin.copy:
    src: /usr/share/cups/model/zjiang/zj58.ppd
    dest: /etc/cups/ppd/Receipt.ppd
    backup: true
    owner: root
    group: lp
    mode: 0664
    remote_src: true
  notify:
    - restart cups

- name: Test laserjet printer ppd
  ansible.builtin.copy:
    src: LaserJet.ppd
    dest: /etc/cups/ppd/LaserJet.ppd
    owner: root
    group: lp
    mode: 0664
  notify:
    - restart cups

- name: Install avahi-discover for airprint
  ansible.builtin.apt:
    pkg: avahi-discover
    state: present
