---
- name: Install Flexget Packages
  ansible.builtin.apt:
    state: present
    pkg:
      - python3
      - virtualenv
      - acl
  tags:
    - flexget
    - media

- name: Do things as the media centre user
  ansible.builtin.import_tasks: media-user-tasks.yml
  become: true
  become_user: "{{ media_user }}"
  tags:
    - flexget
    - media

- name: Setup flexget cron
  ansible.builtin.cron:
    name: flexget
    minute: 16,46
    user: "{{ media_user }}"
    job: "{{ media_home }}/.virtualenvs/flexget/bin/python {{ media_home }}/.virtualenvs/flexget/bin/flexget --cron execute"
    cron_file: flexget
  tags:
    - flexget
    - media
