---
- name: Install required packages
  ansible.builtin.apt:
    package: "{{ item }}"
    state: present
  loop:
    - nginx
    - python3-passlib
    - libnginx-mod-http-fancyindex

- name: Delete old ssl config snippits
  ansible.builtin.file:
    path: /etc/nginx/snippets/{{ item | basename }}
    state: absent
  with_fileglob:
    - templates/ssl/*
  notify:
    - Reload nginx
  tags:
    - streamsite
    - nginx

- name: Configure ssl config snippits
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nginx/snippets/ssl/{{ item | basename }}
    mode: "0644"
  with_fileglob:
    - templates/ssl/*
  notify:
    - Restart nginx
  tags:
    - nginx

- name: Configure config overrides
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nginx/snippets/{{ item | basename }}
    mode: "0644"
  with_fileglob:
    - templates/nginx_snippets/*
  notify:
    - Reload nginx
  tags:
    - nginx

- name: Configure conf.d items
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/{{ item | basename }}
    mode: "0644"
  with_fileglob:
    - templates/nginx_confd/*
  notify:
    - Restart nginx
  tags:
    - nginx

- name: Configure nginx sites as available
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available/{{ item | basename }}
    mode: "0644"
  with_fileglob:
    - templates/vhosts/*
  notify:
    - Restart nginx
  tags:
    - streamsite
    - nginx
    - nginx_sites

- name: Configure nginx sites as enabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/{{ item | basename }}
    src: ../sites-available/{{ item | basename }}
    state: link
    mode: "0644"
  with_fileglob:
    - templates/vhosts/*
  notify:
    - Restart nginx
  tags:
    - streamsite
    - nginx_sites

- name: Configure dead nginx sites as disabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/{{ item | basename }}
    state: absent
  with_fileglob:
    - templates/deleted_vhosts/*
  notify:
    - Restart nginx
  tags:
    - streamsite
    - nginx_sites

- name: Configure dead nginx sites as unavailable
  ansible.builtin.file:
    path: /etc/nginx/sites-available/{{ item | basename }}
    state: absent
  with_fileglob:
    - templates/deleted_vhosts/*
  notify:
    - Restart nginx
  tags:
    - streamsite
    - nginx_sites

- name: Streamsite Basic Auth
  community.general.htpasswd:
    path: /etc/nginx/streamsite.htpass
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    mode: "0644"
  loop: "{{ streamsite_users }}"
  no_log: true
  tags:
    - streamsite
    - nginx_sites
