roles:
  - src: elastic.elasticsearch
    version: v7.16.3
  - src: geerlingguy.java
  - src: elboletaire.transmission
  #- src: pablocrivella.heroku-toolbelt
  - src: https://github.com/aquarion/ansible-papertrail
    name: ansible.papertrail

collections:
 - community.aws