---
roles:
  - src: elastic.elasticsearch
    version: v7.16.3
  - src: geerlingguy.java
    version: 2.2.0
  - src: elboletaire.transmission
    version: 2.0.2
  - src: https://github.com/aquarion/ansible-papertrail
    name: ansible.papertrail

collections:
  - amazon.aws
  - community.general
  - community.mysql
