---


- name: Aquarionics DNS
  include: aquarionics.yml
  tags:
    - aws
    - aquarionics

- include: aqxs.yml
  tags:
    - aws

- include: camlarp.yml
  tags:
    - aws
    - camlarp


- include: cleartext.yml
  tags:
    - aws

- include: factionfiction.yml
  tags:
    - aws

- include: foipme.yml
  tags:
    - aws

- include: warehouse.yml
  tags:
    - aws

- include: monthlymoon.yml
  tags:
    - aws
    - monthlymoon

- include: ludoistic.yml
  tags:
    - aws
    - ludoistic

- include: carcosadreams.yml
  tags:
    - aws
    - carcosadreams


- include: larpfic.yml
  tags:
    - aws
    - larpfic

- include: larpme.yml
  tags:
    - aws
    - larpme

- include: conterio.yml
  tags:
    - aws
    - conterio

- include: hubris.yml
  tags:
    - aws
    - hubris


- include: bromioscreations.yml
  tags:
    - aws
    - bromioscreations

- include: istic.yml
  tags:
    - aws
    - istic_net

- include: nanocountdown.yml
  tags:
    - aws
    - nanocountdown

- include: dagon_church.yml
  tags:
    - aws
    - dagon_church

