---
- name: Fetch plexupdate
  ansible.builtin.git:
    repo: https://github.com/mrworf/plexupdate.git
    dest: /root/plexupdate
    version: master

- name: Set cron plexupdate preferences
  ansible.builtin.template:
    src: plexupdate.cron.conf
    dest: /etc/plexupdate.cron.conf
    mode: "0644"

- name: Set public plexupdate preferences
  ansible.builtin.template:
    src: plexupdate.conf
    dest: /etc/plexupdate.conf
    mode: "0644"

- name: Install plex
  ansible.builtin.command:
    cmd: /root/plexupdate/plexupdate.sh -p -a
    chdir: /tmp
    creates: /etc/init/plexmediaserver.conf

- name: Add cron
  ansible.builtin.file:
    src: /root/plexupdate/extras/cronwrapper
    dest: /etc/cron.daily/plexupdate
    state: link

# # Remove old stuff
- name: Remove old cron for plex update
  ansible.builtin.cron:
    name: plexupdate
    cron_file: plexupdate
    user: root
    hour: 4
    minute: 47
    job: cd /tmp;/root/plexupdate/plexupdate.sh
    state: absent

- name: Remove old plex update
  ansible.builtin.file:
    path: /root/.plexupdate
    state: absent
