#- name: install nginx
#  apt: pkg=nginx state=installed

- name: Create www errors directory
  file: path=/var/www/errors state=directory

- name: configure nginx error pages
  template: src={{item}} dest=/var/www/errors/{{ item | basename }}
  with_fileglob:
   - templates/errors/*

- name: configure nginx base page
  template: src=host_not_found.html dest=/var/www/html/index.html

- name: configure nginx error pages
  template: src=config/errors.conf dest=/etc/nginx/snippets/errors.conf
#  notify:
#   - restart nginx
