---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart redis
  ansible.builtin.service:
    name: redis
    state: restarted

- name: Kick sysctl
  ansible.builtin.command: sysctl -p
