
- name: Install filebot
  include: filebot.yml
  tags:
    - media

- name: Install get_iplayer
  include: iplayer.yml
  tags:
    - media

- name: Disable protected hardlinks (makes filebot hardlink work)
  lineinfile: line="fs.protected_hardlinks = 0" state="present" dest=/etc/sysctl.conf
  notify: sysctl
  tags:
    - media

# Script support
- name: Make sure plex has a bin
  file: path={{ plex_home }}/bin state=directory owner=plex
  tags:
    - media


# Sort It Ahht

- name: Add sortitaaht script to bin
  template: src=sortitaaht.sh dest={{ plex_home }}/bin/sortitaaht.sh mode=0755 owner=plex
  tags:
    - media

- name: Add sortitaaht script to bin
  template: src=sortitaaht.sh dest={{ plex_home }}/bin/sortitaaht_verbose.sh mode=0755 owner=plex
  tags:
    - media
  vars:
    verbose: true


- name: Add sortitaaht script to bin
  template: src=clear_bullshit.sh dest={{ plex_home }}/bin/clear_bullshit.sh mode=0755 owner=plex
  tags:
    - media

- name: Add sortitaaht cron job
  cron: name="filebot" minute="2,32"
        user="plex" job="{{ plex_home }}/bin/sortitaaht.sh | logger --tag Filebot --server={{ plex_remote_syslog_host }} --port={{ plex_remote_syslog_host }}"
        cron_file=filebot
        state=present
  tags:
    - media

- name: Add youtube_download script to bin
  template: src=youtube_download.sh dest={{ plex_home }}/bin/youtube_download.sh mode=0755 owner=plex
  tags:
    - media
    - media_playlists

- name: Add youtube_download cron job
  cron: name="youtube_download" minute="15" hour=3
        user="plex" job="{{ plex_home }}/bin/youtube_download.sh  | logger --server={{ plex_remote_syslog_host }} --port={{ plex_remote_syslog_host }} --tag youtube"
        cron_file=youtube_download
        state=present
  tags:
    - media

- apt:
   state: present
   pkg: 
    - transmission-cli
    - aria2
  tags:
    - media

- apt:
   state: present
   name: transmission-remote-cli
  tags:
    - media

- name: Add remove_completed_torrents script to bin
  template: src=remove_completed_torrents.sh dest={{ plex_home }}/bin/remove_completed_torrents.sh mode=0755 owner=plex
  tags:
    - media


- name: Add remove_completed_torrents cron job
  cron: name="remove_completed_torrents" minute="15" hour=18
        user="plex" job="{{ plex_home }}/bin/remove_completed_torrents.sh  | logger --server={{ plex_remote_syslog_host }} --port={{ plex_remote_syslog_host }} --tag torrent_remove"
        cron_file=remove_completed_torrents
        state=present
  tags:
    - media


- name: Add media logrotate
  template: src=media_logrotate.j2 dest=/etc/logrotate.d/media_logrotate mode=0644 owner=root
  tags:
    - inotify

# On Notify

- name: Install inotify-tools
  apt: package=inotify-tools state=present
  tags:
    - media
    - inotify

- name: Add Notify script to bin
  template: src=inotify.sh dest={{ plex_home }}/bin/inotify.sh mode=0755 owner=plex
  notify: 
    - restart filebot inotify
  tags:
    - media
    - inotify

- name: Add inotify cron job
  cron: name="filebot-notify" special_time=hourly
        user="plex" job="{{ plex_home }}/bin/inotify.sh | logger --server={{ plex_remote_syslog_host }} --port={{ plex_remote_syslog_host }} --tag inotify"
        cron_file=filebot-notify
  tags:
    - media
    - inotify
