
- name: Install filebot
  include: filebot.yml

- name: Disable protected hardlinks (makes filebot hardlink work)
  lineinfile: line="fs.protected_hardlinks = 0" state="present" dest=/etc/sysctl.conf
  notify: sysctl

# Script support
- name: Make sure plex has a bin
  file: path={{ plex_home }}/bin state=directory owner=plex


# Sort It Ahht

- name: Add sortitaaht script to bin
  template: src=sortitaaht.sh dest={{ plex_home }}/bin/sortitaaht.sh mode=0755 owner=plex

- name: Add sortitaaht cron job
  cron: name="filebot" minute="2,32"
        user="plex" job="{{ plex_home }}/bin/sortitaaht.sh"
        cron_file=filebot
        state=absent

# On Notify

- name: Install inotify-tools
  apt: package=inotify-tools state=installed

- name: Add Notify script to bin
  template: src=inotify.sh dest={{ plex_home }}/bin/inotify.sh mode=0755 owner=plex

- name: Add inotify cron job
  cron: name="filebot-notify" special_time=reboot
        user="plex" job="{{ plex_home }}/bin/inotify.sh"
        cron_file=filebot-notify