
- name: "Install B2"
  pip:
   name: b2
  tags:
    - "b2backup"

- name: "Check B2 authorisation"
  lineinfile:
    path: /var/lib/plexmediaserver/.b2_auth_date
    regexp: '^etag'
    line: 'etag {{ backblaze_key_changed }}'
    owner: plex
    group: plex
    mode: 0644
    create: yes
  notify:
    reauthorize backblaze
  tags:
    - "b2backup"

- template: src=media-backup.bash.j2 dest=/var/lib/plexmediaserver/bin/media-backup.sh mode=0770 owner=plex 
  tags:
    - "b2backup"


- cron: name="b2backup" hour=04 minute="46"
        user="plex" job="/var/lib/plexmediaserver/bin/media-backup.sh"
        cron_file=b2backup
  tags:
    - "b2backup"