- name: Install required packages
  apt:
    package: "{{ item }}"
    state: present
  loop:
    - "nginx"
    - "python-passlib"
    - libnginx-mod-http-fancyindex
  tags:
    - streamsite

- name: configure nginx sites as available
  template: src={{ item }} dest=/etc/nginx/sites-available/{{ item | basename }}
  with_fileglob:
   - templates/vhosts/*
  notify:
   - restart nginx
  tags:
   - streamsite

- name: Configure nginx sites as enabled
  file: path=/etc/nginx/sites-enabled/{{ item | basename }} src=../sites-available/{{ item | basename }} state=link
  with_fileglob:
   - templates/vhosts/*
  notify:
   - restart nginx
  tags:
     - streamsite

- name: Configure dead nginx sites as disabled
  file: path=/etc/nginx/sites-enabled/{{ item | basename }} state=absent
  with_fileglob:
   - templates/deleted_vhosts/*
  notify:
   - restart nginx

- name: Configure dead nginx sites as unavailable
  file: path=/etc/nginx/sites-available/{{ item | basename }} state=absent
  with_fileglob:
   - templates/deleted_vhosts/*
  notify:
   - restart nginx

- name: Streamsite Basic Auth
  htpasswd:
    path: /etc/nginx/streamsite.htpass
    name: "{{ item.user }}"
    password: "{{ item.password }}"
  loop: "{{ streamsite_users }}"
  tags:
    - streamsite


- name: Configure nginx redirects
  template: src=config/redirects.nginx.j2 dest=/etc/nginx/conf.d/www_redirects.conf
  vars:
    add_www:
    - aquarionics.com
    - cleartextcontent.co.uk
    - carcosadreams.co.uk
    - deathuntodarkness.org
    remove_www:
    - ludoistic.com
    - omnyom.com
    - factionfiction.net
    - warehousebasement.com
    - hubris.house
  notify:
   - restart nginx
