---
- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Add docker repository to apt
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  tags:
    - docker

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 21600
  loop:
    - docker-ce
    - docker-ce-cli
  tags:
    - docker

- name: Allow docker to access redis
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    line: bind 127.0.0.1 ::1 172.17.0.1
    regex: ^bind
  tags:
    - docker
  notify:
    - restart redis

- name: Make sure docker can access MariaDB
  ansible.builtin.copy:
    src: mysql/docker.cnf
    dest: /etc/mysql/mariadb.conf.d/60-docker.cnf
    owner: root
    mode: "0664"
  tags:
    - docker
  notify:
    - restart mysql

- name: Add users to docker group
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - aquarion
    - ccooke
  tags:
    - docker
