- name: install nginx
  apt: pkg=nginx state=installed

- name: configure letsencrypt config
  template: src=letsencrypt.conf.j2 dest=/etc/nginx/snippets/letsencrypt.conf

- name: Fix diffie-hellman insecurites
  include: diffie-hellman.yml


- name: Add clacks overhead to nginx
  copy: 
    dest: /etc/nginx/conf.d/clacks.conf
    src: files/clacks.conf 
    owner: root 
    group: root
  notify:
   - restart nginx
