

- name: aqxs.net. - A
  route53:
      overwrite: true
      command: "create"
      zone: "aqxs.net"
      record: "aqxs.net."
      type: "A"
      ttl: "3600"
      value: '109.74.192.161'



- name: aqxs.net. - NS
  route53:
      overwrite: true
      command: "create"
      zone: "aqxs.net"
      record: "aqxs.net."
      type: "NS"
      ttl: "172800"
      value: ns-1408.awsdns-48.org., ns-685.awsdns-21.net., ns-40.awsdns-05.com., ns-1866.awsdns-41.co.uk.



#- name: aqxs.net. - SOA
#  route53:
#      overwrite: true
#      command: "create"
#      zone: "aqxs.net"
#      record: "aqxs.net."
#      type: "SOA"
#      ttl: "900"
#      value: 'ns-1408.awsdns-48.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'



- name: aqxs.net. - SPF
  route53:
      overwrite: true
      command: "create"
      zone: "aqxs.net"
      record: "aqxs.net."
      type: "TXT"
      ttl: "300"
      value: '"v=spf1 a mx include:spf.mtasv.net ~all"'

#

- name: aqxs.net. - TXT for google-site-verification
  route53:
      overwrite: true
      command: "create"
      zone: "aqxs.net"
      record: "aqxs.net."
      type: "TXT"
      ttl: "300"
      value: '"google-site-verification=SvTocYjKGCKTzN9BlJSdq0MVkEaFvEAum18VoLaKB5s"'

- name: wildcard.aqxs.net. - A
  route53:
      overwrite: true
      command: "create"
      zone: "aqxs.net"
      record: "*.aqxs.net."
      type: "A"
      ttl: "3600"
      value: '109.74.192.161'



- name: 20151026232244.pm._domainkey.aqxs.net. - TXT
  route53:
      overwrite: true
      command: "create"
      zone: "aqxs.net"
      record: "20151026232244.pm._domainkey.aqxs.net."
      type: "TXT"
      ttl: "300"
      value: '"k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGF2/JFx7pvFw7RU1wXzqtMohMaSZTEbeLscHSrvzrKKtH2M1zTY8YwIZpjFCjbCbQ2aW28bLzzhd2e1klZorwWV++CYoXnnGgVtz1241ToVPgKyKepmBn6E+3DaJZWsj17jINgEkxYoZ3hvp34y+NSFxlMR4bD9V3EetoxUAYgQIDAQAB"'


- name: lists.aqxs.net. - MX
  route53:
      overwrite: true
      command: "delete"
      zone: "aqxs.net"
      record: "lists.aqxs.net."
      type: "MX"
      ttl: "3600"
      value: '10 cenote.gkhs.net.aqxs.net.'

- name: pmbounce.aqxs.net. - CNAME
  route53:
      overwrite: true
      command: "create"
      zone: "aqxs.net"
      record: "pmbounce.aqxs.net."
      type: "CNAME"
      ttl: "300"
      value: 'pm.mtasv.net'

