--- 

- name: CarcosaDreams.co.uk
  route53_zone:
    zone: carcosadreams.co.uk
    comment: CarcosaDreams
    aws_access_key: '{{istic_aws_key}}'
    aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: CarcosaDreams.uk
  route53_zone:
    zone: carcosadreams.uk
    comment: CarcosaDreams
    aws_access_key: '{{istic_aws_key}}'
    aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: CarcosaDreams.com
  route53_zone:
    zone: carcosadreams.com
    comment: CarcosaDreams
    aws_access_key: '{{istic_aws_key}}'
    aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: carcosadreams.co.uk. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: "carcosadreams.co.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: carcosadreams.uk. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.uk"
      record: "carcosadreams.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: www.carcosadreams.co.uk. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: "www.carcosadreams.co.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams



- name: www.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "www.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: www.carcosadreams.uk. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.uk"
      record: "www.carcosadreams.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams



- name: t67.carcosadreams.co.uk. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: "t67.carcosadreams.co.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: forsaken.carcosadreams.co.uk. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: "forsaken.carcosadreams.co.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: alba.carcosadreams.co.uk. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: "alba.carcosadreams.co.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: alba.narrative.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "absent"
      zone: "carcosadreams.com"
      record: "alba.narrative.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: alba-internal.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "alba-internal.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: wiki.carcosadreams.co.uk. - A
  route53:
      overwrite: true
      command: "delete"
      zone: "carcosadreams.co.uk"
      record: "wiki.carcosadreams.co.uk."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: t67.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "t67.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: deadair.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "deadair.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: da-internal.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "da-internal.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: tr-internal.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "tr-internal.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: tabula-rasa.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "tabula-rasa.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: forsaken.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "forsaken.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: sisyphus.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "sisyphus.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: alba.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "alba.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: wiki.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "wiki.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: wiki.carcosadreams.com. - A
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "wiki.carcosadreams.com."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: carcosadreams.co.uk. - MX
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: "carcosadreams.co.uk"
      type: "MX"
      ttl: "300"
      value: '0 carcosadreams-co-uk.mail.protection.outlook.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.com. - MX
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "carcosadreams.com"
      type: "MX"
      ttl: "300"
      value: '0 carcosadreams-com.mail.protection.outlook.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.com. - autodiscover
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: "autodiscover.carcosadreams.com"
      type: "CNAME"
      ttl: "300"
      value: 'autodiscover.outlook.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.co.uk. - autodiscover
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: "autodiscover.carcosadreams.co.uk"
      type: "CNAME"
      ttl: "300"
      value: 'autodiscover.outlook.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.com. - sipdir
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: 'sip.carcosadreams.com'
      type: "CNAME"
      ttl: "300"
      value: 'sipdir.online.lync.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.com. - sipdir.TLS
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: '_sip._tls.carcosadreams.com'
      type: "SRV"
      ttl: "300"
      value: '100 1 443 sipdir.online.lync.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.com. - sipdir.Federated
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: '_sipfederationtls._tcp.carcosadreams.com'
      type: "SRV"
      ttl: "300"
      value: '100 1 5061 sipfed.online.lync.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.com. - lyncdiscover
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: 'lyncdiscover.carcosadreams.com'
      type: "CNAME"
      ttl: "300"
      value: 'webdir.online.lync.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: carcosadreams.com. - enterpriseregistration
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: 'enterpriseregistration.carcosadreams.com'
      type: "CNAME"
      ttl: "300"
      value: 'enterpriseregistration.windows.net.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: carcosadreams.com. - enterpriseenrollment
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: 'enterpriseenrollment.carcosadreams.com'
      type: "CNAME"
      ttl: "300"
      value: 'enterpriseenrollment.manage.microsoft.com.'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


- name: carcosadreams.com. - SPF
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.com"
      record: 'carcosadreams.com'
      type: "TXT"
      ttl: "300"
      value: '"v=spf1 include:spf.protection.outlook.com -all"'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams

- name: carcosadreams.co.uk. - SPF
  route53:
      overwrite: true
      command: "create"
      zone: "carcosadreams.co.uk"
      record: 'carcosadreams.co.uk'
      type: "TXT"
      ttl: "300"
      value: '"v=spf1 include:spf.protection.outlook.com -all"'
      aws_access_key: '{{istic_aws_key}}'
      aws_secret_key: '{{istic_aws_secret}}'
  tags:
    - carcosadreams


