---

- name: hubris.house
  route53_zone:
    state: "present"
    zone: hubris.house
    comment: hubris.house
    aws_access_key: '{{aqcom_aws_key}}'
    aws_secret_key: '{{aqcom_aws_secret}}'
  tags:
    - hubris.house


- name: hubris.house. - A
  route53:
      overwrite: true
      state: "present"
      zone: "hubris.house"
      record: "hubris.house."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{aqcom_aws_key}}'
      aws_secret_key: '{{aqcom_aws_secret}}'
  tags:
    - hubris.house

- name: www.hubris.house. - A
  route53:
      overwrite: true
      state: "absent"
      zone: "hubris.house"
      record: "www.hubris.house."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{aqcom_aws_key}}'
      aws_secret_key: '{{aqcom_aws_secret}}'
  tags:
    - hubris.house


- name: wildcard.hubris.house. - A
  route53:
      overwrite: true
      state: "present"
      zone: "hubris.house"
      record: "*.hubris.house."
      type: "A"
      ttl: "300"
      value: '{{ archipelago_ip }}'
      aws_access_key: '{{aqcom_aws_key}}'
      aws_secret_key: '{{aqcom_aws_secret}}'
  tags:
    - hubris.house