---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Kick sysctl
  ansible.builtin.command: sysctl -p

- name: Update motd
  ansible.builtin.command: update-motd

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
