---
- name: General stream-delta setup
  ansible.builtin.import_tasks: general.yml
- name: Production environment and deploy
  ansible.builtin.import_tasks: deploy_production.yml
- name: Staging environment and deploy
  ansible.builtin.import_tasks: deploy_staging.yml
