---
- name: Install Exim
  ansible.builtin.apt:
    pkg: exim4
    state: present

- name: Add exim to certbot access users
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: "{{ item }}"
    groups: certbot_access
    append: true
  with_items:
    - Debian-exim
  tags:
    - exim

- name: Install update-exim.conf config
  ansible.builtin.template:
    src: update-exim4.conf.conf.j2
    dest: /etc/exim4//update-exim4.conf.conf
    owner: root
    ansible.builtin.group: root
    mode: 0640
    # validate: "update-exim4.conf --check %s"
  tags:
    - exim

- name: Install exim config
  ansible.builtin.template:
    src: exim.conf.j2
    dest: /etc/exim4/conf.d/main/00_water_gkhs_custom
    owner: root
    ansible.builtin.group: root
    mode: 0640
    # validate: "update-exim4.conf --check %s"
  vars:
    cert_id: "{{ letsencrypt_dir }}"
  tags:
    - exim

- name: Set mailname
  ansible.builtin.copy:
    dest: /etc/mailname
    content: "{{ hostname }}"
    mode: 0644
  tags:
    - exim

- name: Check Exim Config before state
  ansible.builtin.stat:
    path: /var/lib/exim4/config.autogenerated
    get_checksum: true
  register: exim_before
  tags:
    - exim

- name: Reconfigure exim
  ansible.builtin.shell: update-exim4.conf
  changed_when: false # Not great, but stops this being a change every run
  tags:
    - exim

- name: Check Exim Config after state
  ansible.builtin.stat:
    path: /var/lib/exim4/config.autogenerated
    get_checksum: true
  register: exim_after
  tags:
    - exim

- name: Restart Exim
  when: exim_before.stat.checksum != exim_after.stat.checksum
  ansible.builtin.service:
    name: exim4
    state: restarted
  tags:
    - exim
