---
galaxy_info:
  author: Nicholas Avenell
  description: Deprovisions Dockerised Laravel apps from firth, archiving data before removal.
  company: Istic Co. <https://istic.co>
  license: GPL-2.0-or-later
  min_ansible_version: "2.1"
  galaxy_tags:
    - docker
    - laravel

dependencies: []
