
tasks:
{% for task in flexget_tasks %}
  {{ task.name }} task:
    rss: {{ task.rss }}
    template: showrss
{% endfor %}

templates:
  showrss:
    accept_all: yes
    transmission:
      host: localhost
      port: 9091
      username: {{ millpond_transmission_user }}
      password: {{ millpond_transmission_pass }}