---
- name: Create normal users
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: "{{ item }}"
  with_items:
    - medialibrary
  tags:
    - users

- name: Delete normal users
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  with_items:
    - arkserver
    - factorio
    - larpfic
  tags:
    - users

- name: Add Aquarion key to users
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/aquarion.keys') }}"
  with_items:
    - medialibrary
  tags:
    - medialibrary
    - users
