---
- name: Install Application Packages
  ansible.builtin.apt:
    state: present
    pkg:
      - mariadb-server
      - irssi
      - exim4

- name: Add PHP PPA
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: absent
  tags: php

- name: Get Launchpad PPA Info
  ansible.builtin.uri:
    url: "https://api.launchpad.net/devel/~ondrej/+archive/ubuntu/php"
    return_content: true
    method: GET
    headers:
      Accept: "application/json"
  register: ondrej_php_ppa_info
  tags: php

- name: Manage PHP PPA repository (deb822_repository)
  become: true
  ansible.builtin.deb822_repository:
    state: present
    name: "ondrej-ubuntu-php-{{ ansible_distribution_release }}"
    types: [deb]
    uris: [https://ppa.launchpadcontent.net/ondrej/php/ubuntu]
    suites: ["{{ ansible_facts['distribution_release'] }}"]
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x{{  ondrej_php_ppa_info.json.signing_key_fingerprint }}"
  tags: php

- name: Remove old PHP Packages
  ansible.builtin.apt:
    state: absent
    pkg:
      - "{{ item }}"
      - "{{ item }}-*"
  loop: "{{ remove_php_versions }}"
  ignore_errors: true
  tags: php

- name: Install PHP With Required Extensions
  ansible.builtin.apt:
    state: present
    pkg:
      - "{{ php_version }}"
      - "{{ php_version }}-bcmath"
      - "{{ php_version }}-cgi"
      - "{{ php_version }}-cli"
      - "{{ php_version }}-common"
      - "{{ php_version }}-curl"
      - "{{ php_version }}-gd"
      - "{{ php_version }}-intl"
      - "{{ php_version }}-mbstring"
      - "{{ php_version }}-mysql"
      - "{{ php_version }}-opcache"
      - "{{ php_version }}-readline"
      - "{{ php_version }}-xml"
  tags: php
