---
- name: Install openssl
  ansible.builtin.apt:
    pkg: openssl
    state: present

- name: Create DHParam file
  ansible.builtin.command:
    cmd: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
    creates: /etc/ssl/certs/dhparam.pem
  notify:
    - restart nginx

- name: Comment out ssl protocols in default config
  ansible.builtin.replace:
    dest: /etc/nginx/nginx.conf
    regexp: ^(\s*)(ssl_protocols.*)
    replace: \1#Ansible#\2

- name: Comment out ssl cipher preferences in default config
  ansible.builtin.replace:
    dest: /etc/nginx/nginx.conf
    regexp: ^(\s*)(ssl_prefer_server_ciphers.*)
    replace: \1#Ansible#\2

- name: Add new DH params to nginx
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/diffie-helman.conf
    src: files/diffie-helman.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
