---
- name: Install nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present

- name: Fix diffie-hellman insecurites
  ansible.builtin.include_tasks: diffie-hellman.yml

- name: Add clacks overhead to nginx
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/clacks.conf
    src: files/clacks.conf
    owner: root
    group: root
    mode: 0664
  notify:
    - Restart nginx

- name: Configure letsencrypt config for misc
  ansible.builtin.template:
    src: letsencrypt.conf.j2
    dest: /etc/nginx/snippets/letsencrypt_ssl.conf
    mode: 0664
  vars:
    cert_id: "{{ letsencrypt_dir }}"

# @todo These should be in Archipelago, really.

- name: Configure letsencrypt config for foip_me
  ansible.builtin.template:
    src: letsencrypt.conf.j2
    dest: /etc/nginx/snippets/foipme_ssl.conf
    mode: 0664
  when: "'archipelago' in inventory_hostname"
  vars:
    cert_id: foip.me
  notify:
    - Restart nginx

- name: Configure letsencrypt config for istic
  ansible.builtin.template:
    src: letsencrypt.conf.j2
    dest: /etc/nginx/snippets/istic_ssl.conf
    mode: 0664
  when: "'archipelago' in inventory_hostname"
  vars:
    cert_id: istic.net
  notify:
    - Restart nginx

- name: Configure letsencrypt config for carcosadreams
  ansible.builtin.template:
    src: letsencrypt.conf.j2
    dest: /etc/nginx/snippets/carcosadreams_ssl.conf
    mode: 0664
  when: "'archipelago' in inventory_hostname"
  vars:
    cert_id: carcosadreams.com
  tags:
    - carcosadreams
  notify:
    - Restart nginx

- name: Configure letsencrypt config for hubris.house
  ansible.builtin.template:
    src: letsencrypt.conf.j2
    dest: /etc/nginx/snippets/hubris_ssl.conf
    mode: 0664
  when: "'archipelago' in inventory_hostname"
  vars:
    cert_id: hubris.house
  tags:
    - hubris.house
  notify:
    - Restart nginx

- name: Configure letsencrypt config for bromioscreations.com
  ansible.builtin.template:
    src: letsencrypt.conf.j2
    dest: /etc/nginx/snippets/bromioscreations_ssl.conf
    mode: 0664
  when: "'archipelago' in inventory_hostname"
  vars:
    cert_id: bromioscreations.com
  tags:
    - bromioscreations
  notify:
    - Restart nginx
