---
- name: Install nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present

- name: Fix diffie-hellman insecurites
  ansible.builtin.include_tasks: diffie-hellman.yml

- name: Add clacks overhead to nginx
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/clacks.conf
    src: files/clacks.conf
    owner: root
    group: root
    mode: "0664"
  notify:
    - Restart nginx
