---

# - name: Create normal users
#   user: name={{ item }}
#   with_items:

- name: Delete normal users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items:
   - arkserver
   - factorio

# - name: Add Aquarion key to arkserver
#   authorized_key: user=factorio key=https://github.com/aquarion.keys
