---

- name: Create normal users
  user: name={{ item }}
  with_items:
    - larpfic

- name: Delete normal users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items:
   - arkserver
   - factorio

- name: Add Aquarion key to users
  authorized_key: user={{ item }} key={{ lookup('file', 'files/aquarion.keys') }}
  with_items:
    - larpfic
    - plex
  tags:
    - larpfic
    - plex
