---
# - name: Install Boto
#   ansible.builtin.pip:
#     state: present
#     name:
#       - boto
#       - botocore
#   tags:
#     - aws
# - name: Install Boto
#   ansible.builtin.apt:
#     state: present
#     name:
#       - python3-boto3
#       - python3-botocore
#   become: true
#   become_method: sudo
#   tags:
#     - aws

- name: Aquarionics DNS - AWS
  ansible.builtin.include_tasks: zones/aquarionics.yml
  tags:
    - aws
    - aquarionics
    - aquarionics_aws

- name: Aquarionics DNS - Cloudflare
  ansible.builtin.include_tasks: zones/aquarionics_cf.yml
  tags:
    - always

- name: Update Route53 for aqxs
  ansible.builtin.include_tasks: zones/aqxs.yml
  tags:
    - aws

- name: Update Route53 for camlarp
  ansible.builtin.include_tasks: zones/camlarp.yml
  tags:
    - aws
    - camlarp

- name: Update Route53 for cleartext
  ansible.builtin.include_tasks: zones/cleartext.yml
  tags:
    - aws

- name: Update Route53 for factionfiction
  ansible.builtin.include_tasks: zones/factionfiction.yml
  tags:
    - aws

- name: Update Route53 for foipme
  ansible.builtin.include_tasks: zones/foipme.yml
  tags:
    - aws

- name: Update Route53 for warehouse
  ansible.builtin.include_tasks: zones/warehouse.yml
  tags:
    - aws

- name: Update Route53 for monthlymoon
  ansible.builtin.include_tasks: zones/monthlymoon.yml
  tags:
    - aws
    - monthlymoon

- name: Update Route53 for ludoistic
  ansible.builtin.include_tasks: zones/ludoistic.yml
  tags:
    - aws
    - ludoistic

- name: Update Route53 for carcosadreams
  ansible.builtin.include_tasks: zones/carcosadreams.yml
  tags:
    - aws
    - carcosadreams

- name: Update Route53 for larpfic
  ansible.builtin.include_tasks: zones/larpfic.yml
  tags:
    - aws
    - larpfic

- name: Update Route53 for larpme
  ansible.builtin.include_tasks: zones/larpme.yml
  tags:
    - aws
    - larpme
    - larpmeuk

- name: Update Route53 for conterio
  ansible.builtin.include_tasks: zones/conterio.yml
  tags:
    - aws
    - conterio

- name: Update Route53 for hubris
  ansible.builtin.include_tasks: zones/hubris.yml
  tags:
    - aws
    - hubris

- name: Update Route53 for bromioscreations
  ansible.builtin.include_tasks: zones/bromioscreations.yml
  tags:
    - aws
    - bromioscreations

- name: Update Route53 for istic
  ansible.builtin.include_tasks: zones/istic.yml
  tags:
    - aws
    - istic_net
    - istic_sys

- name: Update Route53 for nanocountdown
  ansible.builtin.include_tasks: zones/nanocountdown.yml
  tags:
    - aws
    - nanocountdown

- name: Update Route53 for dagon_church
  ansible.builtin.include_tasks: zones/dagon_church.yml
  tags:
    - aws
    - dagon_church

- name: Update Route53 for nicholasavenell
  ansible.builtin.include_tasks: zones/nicholasavenell.yml
  tags:
    - aws
    - nicholasavenell
