---

- name: Install key
  apt_key:
    keyserver: keyring.debian.org
    id: 8B48AD6246925553

- name: Package list update
  apt: update_cache=yes cache_valid_time=21600

- name: Install System Packages
  apt: pkg={{ item }} state=installed
  with_items:
    - python
    - python-pip
    - build-essential
    - libffi-dev
    - libssl-dev
    - apt-transport-https
    - ca-certificates
    - etckeeper
    - fail2ban

- name: config fail2ban
  lineinfile:
    path: /etc/fail2ban/fail2ban.conf
    regexp: '^logtarget'
    line: "logtarget = SYSLOG"
  notify:
    restart fail2ban

- name: Install Utility Packages
  apt: pkg={{ item }} state=installed
  with_items:
      - vim
      - screen
      - git
      - sudo
      - ruby
      - gpw
      - aptitude
      - apticron
      - moreutils
      - rzip

- apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    state: present
    filename: 'stretch-backports'

- name: Install backported packages
  apt: pkg={{ item }} state=installed default_release=stretch-backports
  with_items:
    - certbot
    
