---

- name: Install System Packages
  apt: pkg={{ item }} state=installed
  with_items:
    - python
    - python-pip
    - build-essential
    - libffi-dev
    - libssl-dev
    - apt-transport-https
    - ca-certificates
    - etckeeper

- name: Install Utility Packages
  apt: pkg={{ item }} state=installed
  with_items:
      - vim
      - screen
      - git
      - sudo
      - ruby
      - gpw
      - aptitude
      - apticron
      - etckeeper
      - rzip
      

