---

- name: Set timezone to UTC
  timezone:
    name: UTC

#- name: Install key
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: 8B48AD6246925553
#  when: ansible_distribution == 'Debian'

- name: Package list update
  apt: update_cache=yes cache_valid_time=21600

- name: Install System Packages
  apt:
    state: present
    pkg:
     - python
     - python-pip
     - build-essential
     - libffi-dev
       #- libssl-dev
     - apt-transport-https
     - ca-certificates
     - etckeeper
     - fail2ban
     - dnsutils

- name: config fail2ban
  lineinfile:
    path: /etc/fail2ban/fail2ban.conf
    regexp: '^logtarget'
    line: "logtarget = SYSLOG"
  notify:
    restart fail2ban

- name: Install Utility Packages
  apt:
    state: present
    pkg:
      - vim
      - screen
      - git
      - sudo
      - ruby
      - gpw
      - aptitude
      - apticron
      - moreutils
      - rzip

- name: Install Debian Backports
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    state: present
    filename: 'stretch-backports'
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'

- name: Install ubuntu packages
  apt: 
    state: present
    pkg:
     - software-properties-common
  when: ansible_distribution == 'Ubuntu'
  tags:
    - certbot

- name: Enable universe repository
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
  tags:
    - certbot

- name: Install Ubuntu Certbot Repo
  apt_repository:
    repo: ppa:certbot/certbot
  when: ansible_distribution == 'Ubuntu'
  tags:
    - certbot

- name: Install ubuntu packages
  apt: 
    state: present
    pkg:
     - certbot
     - python-certbot-nginx
  when: ansible_distribution == 'Ubuntu'
  tags:
    - certbot

