---
- name: Aquarionics DNS
  vars:
    _zone: aquarionics.com
    _records:
      - { name: "@", type: A, state: present, value: "{{ loadbalancer_ip }}", ttl: "86400", cf_proxied: true }
      - { name: "@", type: AAAA, state: present, value: "{{ loadbalancer_ipv6 }}", cf_proxied: true }
      - { name: "@", type: TXT, state: present, value: '"v=spf1 include:aspmx.googlemail.com ~all"', ttl: "300" }
      - { name: "@", type: SPF, state: present, value: '"v=spf1 include:aspmx.googlemail.com ~all"', ttl: "86400", r53_only: true }
      - name: _718a5f89a82bf1a5111be33a782c832a
        type: CNAME
        state: present
        value: _02827ed4ad6fed8455c7ece69808224e.hkvuiqjoua.acm-validations.aws.
        ttl: "300"
      - { name: _atproto, type: TXT, state: present, value: '"did=did:plc:acfoshntvxza6ac45bkttyiw"', ttl: "300" }
      - { name: _atproto.twitch, type: TXT, state: present, value: '"did=did:plc:wetrwknoxgx4tik4oewkukkl"', ttl: "300" }
      - name: "_7ca693a0f8f72e0865bf5335a6877adb.cdn"
        type: CNAME
        state: present
        value: _a610429fde9cdbee8f486a8f8ee9c28e.hkvuiqjoua.acm-validations.aws.
        ttl: "300"
      - { name: "*.cdn", type: CNAME, state: present, value: d2r0e8lumqw3g1.cloudfront.net, ttl: "3600" }
      - { name: cdn, type: CNAME, state: present, value: d2r0e8lumqw3g1.cloudfront.net, ttl: "300" }
      - { name: dailyphoto, type: CNAME, state: present, value: dc80vpukp1283.cloudfront.net, ttl: "300" }
      - { name: feeds, type: CNAME, state: present, value: "{{ loadbalancer_domain }}", cf_proxied: true }
      - { name: flix, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - name: google._domainkey
        type: TXT
        state: present
        value: '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeXipYp/HVbmCmGSDI5WKA6vB2679OoStEVKXePsMD0WfEOK+BqQv1lHBzjL2AlNvGmMPf2Ccd6cnk0HdsaQqpkbS1TyOWuZx7P191Q1bHhT5mxvZoAdYbv5XN+0j/SWsqhg/2zYmCQhB8ed499sX5esIUWYQK4djh+xV7GaYxCwIDAQAB"'
        ttl: "300"
      - { name: live, type: CNAME, state: present, value: www.aquarionics.com, ttl: "300" }
      - { name: live.dailyphoto, type: A, state: present, value: "{{ loadbalancer_ip }}", ttl: "300" }
      - { name: live.dailyphoto, type: CNAME, state: absent, value: d2r0e8lumqw3g1.cloudfront.net }
      - { name: mail, type: CNAME, state: present, value: ghs.google.com, ttl: "86400" }
      - { name: old, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - { name: old, type: AAAA, state: present, value: "{{ loadbalancer_ipv6 }}", cf_proxied: true }
      - { name: panopticon, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - { name: stream, type: CNAME, state: present, value: "{{ stream_delta_app_domain }}", ttl: "300" }
      - { name: thalium, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - { name: tumblr, type: CNAME, state: present, value: domains.tumblr.com, ttl: "3600" }
      - { name: vis, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - { name: vtt, type: A, state: present, value: "{{ loadbalancer_ip }}", ttl: "300" }
      - { name: wiki, type: A, state: absent, value: "{{ loadbalancer_ip }}" }
      - { name: wiki, type: AAAA, state: absent, value: "{{ loadbalancer_ipv6 }}" }
      - { name: wiki, type: CNAME, state: present, value: publish-main.obsidian.md, cf_proxied: true }
      - { name: www, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - { name: wywo, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
    _mx:
      - { r53: "1 ASPMX.L.GOOGLE.COM.", cf_value: ASPMX.L.GOOGLE.COM., cf_priority: 1 }
      - { r53: "5 ALT1.ASPMX.L.GOOGLE.COM.", cf_value: ALT1.ASPMX.L.GOOGLE.COM., cf_priority: 5 }
      - { r53: "5 ALT2.ASPMX.L.GOOGLE.COM.", cf_value: ALT2.ASPMX.L.GOOGLE.COM., cf_priority: 5 }
      - { r53: "10 ALT3.ASPMX.L.GOOGLE.COM.", cf_value: ALT3.ASPMX.L.GOOGLE.COM., cf_priority: 10 }
      - { r53: "10 ALT4.ASPMX.L.GOOGLE.COM.", cf_value: ALT4.ASPMX.L.GOOGLE.COM., cf_priority: 10 }
  block:
    - name: Aquarionics Route53 DNS
      tags:
        - aws
        - aquarionics
        - aquarionics_aws
      block:
        - name: "Aquarionics.com Route53 {{ item.name ~ ' ' ~ item.type }}"
          amazon.aws.route53:
            overwrite: true
            state: "{{ item.state }}"
            zone: "{{ _zone }}"
            record: "{{ (item.name == '@') | ternary(_zone + '.', item.name + '.' + _zone + '.') }}"
            aws_profile: aqcom
            type: "{{ item.type }}"
            ttl: "{{ item.ttl | default('300') }}"
            value: "{{ item.value }}"
          loop: "{{ _records | rejectattr('cf_only', 'defined') | list }}"
          loop_control:
            label: "{{ item.name }} {{ item.type }}"

        - name: Aquarionics.com Route53 MX
          amazon.aws.route53:
            overwrite: true
            state: present
            zone: "{{ _zone }}"
            record: "{{ _zone }}."
            aws_profile: aqcom
            type: MX
            ttl: "300"
            value: "{{ _mx | map(attribute='r53') | join(',') }}"

      rescue:
        - name: Failure warning
          ansible.builtin.debug:
            msg: AWS Route53 tasks failed
        - name: Failure execution
          ansible.builtin.command:
            cmd: "false"

    - name: Aquarionics Cloudflare DNS
      tags:
        - aws
        - aquarionics
        - aquarionics_aws
        - cloudflare
        - cloudflare_dns
      block:
        - name: "Aquarionics.com CF {{ item.name ~ ' ' ~ item.type }}"
          community.general.cloudflare_dns:
            state: "{{ item.state }}"
            zone: "{{ _zone }}"
            record: "{{ item.name }}"
            api_token: "{{ cloudflare_api_key }}"
            type: "{{ item.type }}"
            ttl: "{{ item.ttl | default(omit) }}"
            value: "{{ item.value }}"
            proxied: "{{ item.cf_proxied | default(false) }}"
          loop: "{{ _records | rejectattr('r53_only', 'defined') | list }}"
          loop_control:
            label: "{{ item.name }} {{ item.type }}"

        - name: Aquarionics.com CF MX
          community.general.cloudflare_dns:
            state: present
            zone: "{{ _zone }}"
            record: "@"
            api_token: "{{ cloudflare_api_key }}"
            type: MX
            value: "{{ item.cf_value }}"
            priority: "{{ item.cf_priority }}"
          loop: "{{ _mx }}"
          loop_control:
            label: "MX {{ item.cf_priority }} {{ item.cf_value }}"
          ignore_errors: true

      rescue:
        - name: Failure warning
          ansible.builtin.debug:
            msg: Cloudflare DNS tasks failed
        - name: Failure execution
          ansible.builtin.command:
            cmd: "false"
