---
- name: Kastark.co.uk.
  amazon.aws.route53_zone:
    state: present
    zone: kastark.co.uk.
    comment: K A Stark
    aws_profile: aqcom
  tags:
    - kastark

- name: Kastark.co.uk. - A
  amazon.aws.route53:
    overwrite: true
    command: present
    zone: kastark.co.uk
    record: kastark.co.uk.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
  tags:
    - kastark

- name: Www.kastark.co.uk. - CNAME - Delete (replace with A record)
  amazon.aws.route53:
    overwrite: true
    command: delete
    zone: kastark.co.uk
    record: www.kastark.co.uk.
    aws_profile: aqcom
    type: CNAME
    ttl: "300"
    value: "kastark.co.uk."
  tags:
    - kastark

- name: Www.kastark.co.uk. - A
  amazon.aws.route53:
    overwrite: true
    command: present
    zone: kastark.co.uk
    record: www.kastark.co.uk.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
  tags:
    - kastark

- name: Dhmstark.co.uk.
  amazon.aws.route53_zone:
    state: present
    zone: dhmstark.co.uk.
    comment: D H M Stark (redirects to kastark.co.uk)
    aws_profile: aqcom
  tags:
    - kastark

- name: Dhmstark.co.uk. - A
  amazon.aws.route53:
    overwrite: true
    command: present
    zone: dhmstark.co.uk
    record: dhmstark.co.uk.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
  tags:
    - kastark

- name: Www.dhmstark.co.uk. - A
  amazon.aws.route53:
    overwrite: true
    command: present
    zone: dhmstark.co.uk
    record: www.dhmstark.co.uk.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
  tags:
    - kastark
