---
- name: Remove plexupdate
  ansible.builtin.file:
    path: /root/plexupdate
    state: absent

- name: Delete cron plexupdate preferences
  ansible.builtin.file:
    state: absent
    path: /etc/plexupdate.cron.conf

- name: Delete public plexupdate preferences
  ansible.builtin.file:
    state: absent
    path: /etc/plexupdate.conf

- name: Remove plex
  ansible.builtin.file:
    state: absent
    path: /etc/init/plexmediaserver.conf

- name: Remove plex
  ansible.builtin.apt:
    package: plexmediaserver
    state: absent
    autoclean: true
    autoremove: true
    purge: true

- name: Remove cron
  ansible.builtin.file:
    path: /etc/cron.daily/plexupdate
    state: absent

# # Remove old stuff
- name: Remove old cron for plex update
  ansible.builtin.cron:
    name: plexupdate
    cron_file: plexupdate
    user: root
    hour: 4
    minute: 47
    job: cd /tmp;/root/plexupdate/plexupdate.sh
    state: absent

- name: Remove old plex update
  ansible.builtin.file:
    path: /root/.plexupdate
    state: absent
