- name: "Create directories {{ retort_install_location }}"
  file: path={{ retort_install_location }} state=directory mode=0755 owner={{ retort_run_user }} group={{ retort_run_group }}

- name: "Create service directories ={{ retort_install_location }}/service"
  file: path={{ retort_install_location }}/service state=directory mode=0755 owner={{ retort_run_user }} group={{ retort_run_group }}

- name: Checkout
  git: repo=https://github.com/aquarion/retort.git dest={{ retort_install_location }}/code accept_hostkey=True
  become: yes
  become_user: "{{ retort_run_user }}"
  notify:
   - restart retort

- name: Checkout owner
  file: path={{ retort_install_location }}/code owner={{ retort_run_user }} group={{ retort_run_group }} recurse=True  

- name: Python libraries
  pip: requirements={{ retort_install_location }}/code/requirements.pip virtualenv={{ retort_install_location }}/venv
  notify:
   - restart retort

- name: Service
  template: src=systemd.tpl.j2 dest=/etc/systemd/system/retort.service
  notify:
   - reload systemd daemon
   - restart retort

- name: Service Socket
  template: src=socket.tpl.j2 dest=/etc/systemd/system/retort.socket
  notify:
   - reload systemd daemon
   - restart retort

- name: Enable Service
  service: name=retort enabled=true

- name: Configure apache
  template: src=apache.conf.h2 dest=/etc/apache2/sites-available/retort.conf
  notify:
   - restart apache2

- name: Enable site
  file: path=/etc/apache2/sites-enabled/000-retort.conf src=/etc/apache2/sites-available/retort.conf state=link
  notify:
   - restart apache2
