# {{ ansible_managed }}
map $http_origin $cors_origin_ludoistic {
    default "";
    "~^https://([a-zA-Z0-9-]+\.)?istic\.net$" $http_origin;
    "~^https://([a-zA-Z0-9-]+\.)?ludoistic\.net$" $http_origin;
}
