nginx_add_www:
  - aquarionics.com
  - cleartextcontent.co.uk
  - carcosadreams.co.uk
  - deathuntodarkness.org
nginx_remove_www:
  - ludoistic.com
  - omnyom.com
  - factionfiction.net
  - warehousebasement.com
  - hubris.house
