---
signoz_ingester_hostname: ingester
## Rest are defauilt values from group_vars/all/70-signoz.yml
# signoz_ingester_grpc_port: 4317
# signoz_ingester_http_port: 4318
# signoz_ingester_scheme: http
# signoz_ingester_is_insecure: "true"
# signoz_ingester_default_protocol: http/protobuf
