---
- name: Install B2
  ansible.builtin.pip:
    name: "b2=={{ b2_version }}"
  tags:
    - b2backup

- name: Check B2 authorisation
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.b2_auth_date"
    regexp: ^etag
    line: etag {{ backblaze_key_changed }}
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: "0644"
    create: true
  notify: Reauthorize backblaze
  tags:
    - b2backup

- name: Setup B2 backup of Media (Script)
  ansible.builtin.template:
    src: media-backup.bash.j2
    dest: "{{ media_home }}/bin/media-backup.sh"
    mode: "0770"
    owner: "{{ media_user }}"
  tags:
    - b2backup

- name: Setup B2 backup of Media (Cron)
  ansible.builtin.cron:
    name: b2backup
    hour: "04"
    minute: "46"
    user: "{{ media_user }}"
    job: "{{ media_home }}/bin/media-backup.sh"
    cron_file: b2backup
  tags:
    - b2backup
