    ssl_certificate /etc/letsencrypt/live/bloomfeed.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bloomfeed.app/privkey.pem;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout 10m;
