---

- hosts: all
  become: yes
  roles:
   - water-gkhs-packages
   - water-gkhs-update

- include: playbook-archipelago.yml
- include: playbook-millpond.yml
- include: playbook-cenote.yml
#- include: playbook-droplet.yml
