---

- hosts: all:!localactions
  become: yes
  roles:
   - water-gkhs-packages
   - water-gkhs-listchanges
   - water-gkhs-update
   - water-gkhs-network
   - water-gkhs-users
   - { role: "ansible.papertrail", tags: papertrail }
   - { role: water-gkhs-web-errors, tags: nginx }

- hosts: archipelago_cenote
  become: yes
  roles:
    - { role: water-gkhs-mysql-backup, tags: mysql }

- hosts: nginx_hosts
  become: yes
  roles:
    - { role: water-gkhs-nginx, tags: nginx }

- hosts: archipelago.water.gkhs.net
  become: yes
  roles:
    - archipelago-packages
    - archipelago-users
    - plexupdate
    # - archipelago-mount-storagebox
    - { role: aws-aqcom-dns, become: no, connection: local }
    - { role: larpme, tags: larpme }
    - { role: aws-pdforums , tags: pdforum }
    - { role: archipelago-nginx, tags: nginx }
    - water-gkhs-filebot
    - water-gkhs-flexget
    - b2-backup
  tasks:
    - user: name={{ item }} groups=docker append=yes
      with_items:
       - aquarion
       - ccooke

# Non-authenticated tasks
- hosts: all:!localactions
  roles:
   - aquarion-bootstrap
