---

- hosts: all
  become: yes
  roles:
   - water-gkhs-packages
   - water-gkhs-listchanges
   - water-gkhs-update
   - { role: "azavea.papertrail", tags: papertrail }
- include: playbook-archipelago.yml
- include: playbook-millpond.yml
- include: playbook-cenote.yml
#- include: playbook-droplet.yml

# Non-authenticated tasks
- hosts: all
  roles:
   - aquarion-bootstrap
