---

- hosts: cenote.water.gkhs.net
  vars:
   - hostname: cenote.water.gkhs.net
  become: yes
  roles:
    - water-gkhs-network
    - water-gkhs-users
    #- pablocrivella.heroku-toolbelt # This needs to suck less
    - { role: water-gkhs-mysql-backup, tags: mysql }
