---
- name: Factionfiction.net. - A
  amazon.aws.route53:
    overwrite: true
    command: create
    zone: factionfiction.net
    record: factionfiction.net.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"

- name: Factionfiction.net. - NS
  amazon.aws.route53:
    overwrite: true
    command: create
    zone: factionfiction.net
    record: factionfiction.net.
    aws_profile: aqcom
    type: NS
    ttl: "172800"
    value: ns-1302.awsdns-34.org.,ns-1969.awsdns-54.co.uk.,ns-147.awsdns-18.com.,ns-614.awsdns-12.net.

# - name: Factionfiction.net. - SOA
#  amazon.aws.route53:
#      overwrite: true
#      command: "create"
#      zone: "factionfiction.net"
#      record: "factionfiction.net."
#      aws_access_key: '{{ aqcom_aws_key }}'
#      aws_secret_key: '{{ aqcom_aws_secret }}'
#      type: "SOA"
#      ttl: "900"
#      value: 'ns-1302.awsdns-34.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'

- name: Www.factionfiction.net. - CNAME
  amazon.aws.route53:
    overwrite: true
    command: create
    zone: factionfiction.net
    record: www.factionfiction.net.
    aws_profile: aqcom
    type: CNAME
    ttl: "300"
    value: factionfiction.net
