---

- name: Create Admin Users
  user: name={{ item }} groups=adm append=yes
  with_items:
   - aquarion
   - ccooke
  tags:
    - users

- name: Ensure group "certbot_access" exists
  group:
    name: certbot_access
    state: present
  tags:
    - users

- name: Add keys key
  with_items:
   - aquarion
   - ccooke
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/' ~  item ~ '.keys') }}"
    exclusive: true
  tags:
    - users

- name: add sudo
  template:
    dest=/etc/sudoers.d/{{ item }}
    src=sudo.tpl
    owner=root
    group=root
    mode=440
    force=yes
    validate='visudo -cf %s'
  with_items:
    - aquarion
    - ccooke
  tags:
    - users


- name: Send admin emails to aquarion
  ansible.builtin.copy:
    content: 'nicholas+{{ inventory_hostname_short }}-cron@aquarionics.com'
    dest: "~{{ item }}/.forward"
  with_items:
    - aquarion
    - root
  tags:
    - users
