---
- name: Create Admin Users
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: "{{ item }}"
    groups: adm
    append: true
  with_items:
    - aquarion
    - ccooke
  tags:
    - users

- name: Ensure group "certbot_access" exists
  ansible.builtin.group:
    name: certbot_access
    state: present
  tags:
    - users

- name: Add keys key
  with_items:
    - aquarion
    - ccooke
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/' ~  item ~ '.keys') }}"
    exclusive: true
  tags:
    - users

- name: Add sudo
  ansible.builtin.template:
    dest: /etc/sudoers.d/{{ item }}
    src: sudo.tpl
    owner: root
    group: root
    mode: ug=r,o=
    force: true
    validate: visudo -cf %s
  with_items:
    - aquarion
    - ccooke
  tags:
    - users

- name: Send admin emails to aquarion
  ansible.builtin.copy:
    content: nicholas+{{ inventory_hostname_short }}-cron@aquarionics.com
    dest: ~{{ item }}/.forward
    mode: a=rw
  with_items:
    - aquarion
    - root
  tags:
    - users
