---
- name: Restart supervisor
  ansible.builtin.systemd:
    name: supervisor
    state: restarted
  tags:
    - supervisord
    - restart
    - supervisor_restart

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - systemd
    - reload
