---
- name: Istic.dev DNS
  vars:
    _zone: istic.dev
    _records:
      - { name: "@", type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - { name: "*", type: CNAME, state: present, value: tributary.water.gkhs.net, cf_proxied: false }
      - { name: novelathon, type: A, state: present, value: "{{ loadbalancer_ip }}", cf_proxied: true }
      - { name: voyeur, type: A, state: present, value: "{{ atoll_ip }}", cf_proxied: true }
      - { name: ws.voyeur, type: A, state: present, value: "{{ atoll_ip }}", cf_proxied: true }
  block:
    - name: Istic.dev Route53 DNS
      tags:
        - aws
        - istic_dev
        - istic_dev_aws
      block:
        - name: "Istic.dev Route53 {{ item.name ~ ' ' ~ item.type }}"
          amazon.aws.route53:
            overwrite: true
            state: "{{ item.state }}"
            zone: "{{ _zone }}"
            record: "{{ (item.name == '@') | ternary(_zone + '.', item.name + '.' + _zone + '.') }}"
            aws_profile: istic
            type: "{{ item.type }}"
            ttl: "{{ item.ttl | default('300') }}"
            value: "{{ item.value }}"
          loop: "{{ _records | rejectattr('cf_only', 'defined') | list }}"
          loop_control:
            label: "{{ item.name }} {{ item.type }}"

      rescue:
        - name: Failure warning
          ansible.builtin.debug:
            msg: AWS Route53 tasks failed
        - name: Failure execution
          ansible.builtin.command:
            cmd: "false"

    - name: Istic.dev Cloudflare DNS
      tags:
        - cloudflare
        - cloudflare_dns
        - istic_dev
      block:
        - name: "(CF) Istic.dev {{ item.name ~ ' ' ~ item.type }}"
          community.general.cloudflare_dns:
            state: "{{ item.state }}"
            zone: "{{ _zone }}"
            record: "{{ item.name }}"
            api_token: "{{ cloudflare_api_key }}"
            type: "{{ item.type }}"
            ttl: "{{ item.ttl | default(omit) }}"
            value: "{{ item.value }}"
            proxied: "{{ item.cf_proxied | default(false) }}"
          loop: "{{ _records | rejectattr('r53_only', 'defined') | list }}"
          loop_control:
            label: "{{ item.name }} {{ item.type }}"

      rescue:
        - name: Failure warning
          ansible.builtin.debug:
            msg: Cloudflare DNS tasks failed
        - name: Failure execution
          ansible.builtin.command:
            cmd: "false"

    - name: Delegate istic.dev to Cloudflare on Namecheap
      ansible.builtin.include_tasks: ../../included_tasks/namecheap_delegate.yml
      vars:
        namecheap_sld: istic
        namecheap_tld: dev
        namecheap_nameservers: carol.ns.cloudflare.com,phil.ns.cloudflare.com
      tags:
        - istic_dev
        - namecheap
