
- name: Install Kiosk Packages
  apt: pkg={{ item }} state=installed
  with_items:
   - x11-common
   - chromium-browser
   - lightdm

- name: Setup Kiosk user
  user: name=kiosk

- name: Ensures xsessions dir exists
  file: path={{item}} state=directory
  with_items:
   - /etc/lightdm/lightdm.conf.d
   - /usr/share/xsessions

- name: Setup kiosk xsession
  template: src=kiosk.desktop dest=/usr/share/xsessions/kiosk.desktop

- name: Setup kiosk launch script
  template: src=chromeKiosk.sh dest=/usr/share/xsessions/chromeKiosk.sh mode=0755

- name: Setup autologin
  template: src=lightdm-autologin.conf dest=/etc/lightdm/lightdm.conf.d/50-autologin.conf

- name: Set kiosk's xsession
  template: src=dmrc.conf dest=/home/kiosk/.dmrc mode=0444 owner=kiosk
