---
- name: Remove Redis ACL user for {{ flr_ctx.name }}
  ansible.builtin.lineinfile:
    path: /etc/redis/users.acl
    regexp: "^user {{ flr_ctx.redis.username | regex_escape }} "
    state: absent
  notify: Reload Redis ACL
  tags: firth_laravel_app_remove
