---
- name: Install System Packages
  ansible.builtin.apt:
    pkg: apt-listchanges
    state: present
  tags:
    - listchanges

- name: Config list-changes
  ansible.builtin.lineinfile:
    path: /etc/apt/listchanges.conf
    regexp: ^email_address
    line: email_address='nicholas+{{ ansible_hostname }}cron@aquarionics.com'
  tags:
    - listchanges
