---
- name: Aquarionics AWS Tasks
  tags:
    - aws
    - aquarionics_aws
    - aquarionics
  block:
    - name: Aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "86400"
        value: "{{ loadbalancer_ip }}"

    - name: Aquarionics.com. - AAAA
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: aquarionics.com.
        aws_profile: aqcom
        type: AAAA
        ttl: "300"
        value: "{{ ansible_default_ipv6.address }}"

    - name: Aquarionics.com. - MX
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: aquarionics.com.
        aws_profile: aqcom
        type: MX
        ttl: "300"
        value: 1 ASPMX.L.GOOGLE.COM.,5 ALT1.ASPMX.L.GOOGLE.COM.,5 ALT2.ASPMX.L.GOOGLE.COM.,10 ALT3.ASPMX.L.GOOGLE.COM.,10 ALT4.ASPMX.L.GOOGLE.COM.

    # - name: Aquarionics.com. - NS
    #   amazon.aws.route53:
    #     overwrite: true
    #     command: create
    #     zone: aquarionics.com
    #     record: aquarionics.com.
    #     aws_profile: aqcom
    #     type: NS
    #     ttl: "172800"
    #     value: ns-1103.awsdns-09.org.,ns-1667.awsdns-16.co.uk.,ns-275.awsdns-34.com.,ns-1004.awsdns-61.net.

    # - name: Aquarionics.com. - SOA
    #  amazon.aws.route53:
    #      overwrite: true
    #      command: "create"
    #      zone: "aquarionics.com"
    #      record: "aquarionics.com."
    #      aws_access_key: '{{ aqcom_aws_key }}'
    # aws_secret_key: '{{ aqcom_aws_secret }}'
    # type: "SOA"
    #      ttl: "900"
    #      value: 'ns-1103.awsdns-09.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'

    - name: Aquarionics.com. - SPF
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: aquarionics.com.
        aws_profile: aqcom
        type: SPF
        ttl: "86400"
        value: '"v=spf1 include:aspmx.googlemail.com ~all"'

    - name: Aquarionics.com. - TXT
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: aquarionics.com.
        aws_profile: aqcom
        type: TXT
        ttl: "300"
        value: '"v=spf1 include:aspmx.googlemail.com ~all"'

    - name: Google._domainkey.aquarionics.com. - TXT
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: google._domainkey.aquarionics.com.
        aws_profile: aqcom
        type: TXT
        ttl: "300"
        value: '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeXipYp/HVbmCmGSDI5WKA6vB2679OoStEVKXePsMD0WfEOK+BqQv1lHBzjL2AlNvGmMPf2Ccd6cnk0HdsaQqpkbS1TyOWuZx7P191Q1bHhT5mxvZoAdYbv5XN+0j/SWsqhg/2zYmCQhB8ed499sX5esIUWYQK4djh+xV7GaYxCwIDAQAB"'

    - name: Stream.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: stream.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "300"
        value: www.aquarionics.com

    - name: Live.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: live.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "300"
        value: www.aquarionics.com

    - name: Cdn.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: cdn.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "300"
        value: d2r0e8lumqw3g1.cloudfront.net

    - name: Amazon DNS Validation for aqcom - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: _718a5f89a82bf1a5111be33a782c832a.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "300"
        value: _02827ed4ad6fed8455c7ece69808224e.hkvuiqjoua.acm-validations.aws.

    - name: Amazon DNS Validation for cdn.aqcom - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: _7ca693a0f8f72e0865bf5335a6877adb.cdn.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "300"
        value: _a610429fde9cdbee8f486a8f8ee9c28e.hkvuiqjoua.acm-validations.aws.

    - name: \*.cdn.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: "*.cdn.aquarionics.com."
        aws_profile: aqcom
        type: CNAME
        ttl: "3600"
        value: d2r0e8lumqw3g1.cloudfront.net

    - name: 1.cdn.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: delete
        zone: aquarionics.com
        record: live.dailyphoto.aquarionics.com.
        aws_profile: aqcom
        value: d2r0e8lumqw3g1.cloudfront.net
        type: CNAME

    - name: 2.cdn.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: delete
        zone: aquarionics.com
        record: live.dailyphoto.aquarionics.com.
        value: d2r0e8lumqw3g1.cloudfront.net
        aws_profile: aqcom
        type: CNAME

    - name: 3.cdn.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: delete
        zone: aquarionics.com
        record: live.dailyphoto.aquarionics.com.
        value: d2r0e8lumqw3g1.cloudfront.net
        aws_profile: aqcom
        type: CNAME

    - name: 4.cdn.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: delete
        zone: aquarionics.com
        record: live.dailyphoto.aquarionics.com.
        value: d2r0e8lumqw3g1.cloudfront.net
        aws_profile: aqcom
        type: CNAME

    - name: Dailyphoto.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: dailyphoto.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "300"
        value: dc80vpukp1283.cloudfront.net

    - name: Live.dailyphoto.aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: live.dailyphoto.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"

    - name: Feeds.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: feeds.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "3600"
        value: "{{ loadbalancer_domain }}"

    - name: Mail.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: mail.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "86400"
        value: ghs.google.com

    - name: Thalium. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: thalium.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "86400"
        value: "{{ loadbalancer_ip }}"

    - name: Old.aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: old.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "86400"
        value: "{{ loadbalancer_ip }}"

    - name: Old.aquarionics.com. - AAAA
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: old.aquarionics.com.
        aws_profile: aqcom
        type: AAAA
        ttl: "300"
        value: "{{ ansible_default_ipv6.address }}"

    - name: Tumblr.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: tumblr.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "3600"
        value: domains.tumblr.com

    - name: Wiki.aquarionics.com. - AAAA
      amazon.aws.route53:
        overwrite: true
        command: delete
        zone: aquarionics.com
        record: wiki.aquarionics.com.
        aws_profile: aqcom
        type: AAAA
        ttl: "300"
        value: "{{ ansible_default_ipv6.address }}"

    - name: Wiki.aquarionics.com. - CNAME
      amazon.aws.route53:
        overwrite: true
        command: delete
        zone: aquarionics.com
        record: wiki.aquarionics.com.
        aws_profile: aqcom
        type: CNAME
        ttl: "86400"
        value: aquarion.github.io

    - name: Wiki.aquarionics.com. - A
      amazon.aws.route53:
        aws_profile: aqcom
        type: A
        ttl: "86400"
        zone: aquarionics.com
        record: wiki.aquarionics.com.
        value: "{{ loadbalancer_ip }}"
        command: create

    - name: Www.aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: www.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"

    - name: Wywo.aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: wywo.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"

    - name: Vis.aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: vis.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"
      tags:
        - streamsite

    - name: Vtt.aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: vtt.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"
      tags:
        - foundryvtt

    - name: Panopticon.aquarionics.com. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: panopticon.aquarionics.com.
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"

    - name: Aquarionics.com. - BlueSky Validation
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: aquarionics.com
        record: _atproto.aquarionics.com
        aws_profile: aqcom
        type: TXT
        ttl: "300"
        value: '"did=did:plc:acfoshntvxza6ac45bkttyiw"'

  rescue:
    - name: "Failure warning"
      ansible.builtin.debug:
        msg: "AWS tasks failed"
    - name: "Failure execution"
      ansible.builtin.command:
        cmd: "false"
