---
- name: Create Camlarp.co.uk DNS records
  tags:
    - camlarp
  when: loadbalancer_ip is defined

  block:
    - name: Camlarp.co.uk. - A
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: camlarp.co.uk
        record: camlarp.co.uk.
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"

    - name: Camlarp.co.uk. - NS
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: camlarp.co.uk
        record: camlarp.co.uk.
        aws_profile: aqcom
        type: NS
        ttl: "172800"
        value: ns-422.awsdns-52.com,ns-617.awsdns-13.net,ns-1181.awsdns-19.org,ns-1809.awsdns-34.co.uk

    # - name: Camlarp.co.uk. - SOA
    #  amazon.aws.route53:
    #      overwrite: true
    #      command: "create"
    #      zone: "camlarp.co.uk"
    #      record: "camlarp.co.uk."
    #      aws_access_key: '{{ aqcom_aws_key }}'
    # aws_secret_key: '{{ aqcom_aws_secret }}'
    # type: "SOA"
    #      ttl: "900"
    #      value: 'ns-422.awsdns-52.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'

    - name: "[event].camlarp.co.uk. - A"
      amazon.aws.route53:
        overwrite: true
        command: create
        zone: camlarp.co.uk
        record: "{{ item }}"
        aws_profile: aqcom
        type: A
        ttl: "300"
        value: "{{ loadbalancer_ip }}"
      loop:
        - bw.camlarp.co.uk.
        - citadel.camlarp.co.uk.
        - darkmoon.camlarp.co.uk.
        - fallingsky.camlarp.co.uk.
        - lovelace.camlarp.co.uk.
        - nfnc.camlarp.co.uk.
        - norseangels.camlarp.co.uk.
        - obscura.camlarp.co.uk.
        - refs.bw.camlarp.co.uk.
        - refs.nfnc.camlarp.co.uk.
        - uh.camlarp.co.uk.
        - www.camlarp.co.uk.

  rescue:
    - name: "Failure warning"
      ansible.builtin.debug:
        msg: "AWS tasks failed"
    - name: "Failure execution"
      ansible.builtin.command:
        cmd: "false"
