---
- name: Conterio.co.uk.
  amazon.aws.route53_zone:
    state: present
    zone: conterio.co.uk.
    comment: Michael Conterio
    aws_profile: aqcom
  tags:
    - conterio

- name: Conterio.co.uk. - A
  amazon.aws.route53:
    overwrite: true
    command: create
    zone: conterio.co.uk
    record: conterio.co.uk.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ cenote_ip }}"
  tags:
    - conterio

# - name: Conterio.co.uk. - NS
#   amazon.aws.route53:
#       overwrite: true
#       command: "create"
#       zone: "conterio.co.uk"
#       record: "conterio.co.uk."
#       aws_access_key: '{{ aqcom_aws_key }}'
#       aws_secret_key: '{{ aqcom_aws_secret }}'
#       type: "NS"
#       ttl: "172800"
#       value: ns-422.awsdns-52.com,ns-617.awsdns-13.net,ns-1181.awsdns-19.org,ns-1809.awsdns-34.co.uk

# - name: Conterio.co.uk. - SOA
#  amazon.aws.route53:
#      overwrite: true
#      command: "create"
#      zone: "conterio.co.uk"
#      record: "conterio.co.uk."
#      aws_access_key: '{{ aqcom_aws_key }}'
# aws_secret_key: '{{ aqcom_aws_secret }}'
# type: "SOA"
#      ttl: "900"
#      value: 'ns-422.awsdns-52.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'

- name: Michael.conterio.co.uk. - A
  amazon.aws.route53:
    overwrite: true
    command: create
    zone: conterio.co.uk
    record: michael.conterio.co.uk.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ cenote_ip }}"
  tags:
    - conterio

- name: Www.conterio.co.uk. - A
  amazon.aws.route53:
    overwrite: true
    command: create
    zone: conterio.co.uk
    record: www.conterio.co.uk.
    aws_profile: aqcom
    type: A
    ttl: "300"
    value: "{{ cenote_ip }}"
  tags:
    - conterio
