---
- name: Larpfic.com
  amazon.aws.route53_zone:
    state: present
    zone: larpfic.com
    comment: larpfic
    aws_profile: aqcom
  tags:
    - larpfic

- name: Lrpfic.com
  amazon.aws.route53_zone:
    state: present
    zone: lrpfic.com
    comment: lrpfic
    aws_profile: aqcom
  tags:
    - larpfic

- name: Larpfic.com. - A
  amazon.aws.route53:
    overwrite: true
    state: present
    zone: larpfic.com
    record: larpfic.com.
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
    aws_profile: aqcom
  tags:
    - larpfic

- name: Www.larpfic.com. - A
  amazon.aws.route53:
    overwrite: true
    state: present
    zone: larpfic.com
    record: www.larpfic.com.
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
    aws_profile: aqcom
  tags:
    - larpfic

- name: Lrpfic.com. - A
  amazon.aws.route53:
    overwrite: true
    state: present
    zone: lrpfic.com
    record: lrpfic.com.
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
    aws_profile: aqcom
  tags:
    - larpfic

- name: Www.lrpfic.com. - A
  amazon.aws.route53:
    overwrite: true
    state: present
    zone: lrpfic.com
    record: www.lrpfic.com.
    type: A
    ttl: "300"
    value: "{{ loadbalancer_ip }}"
    aws_profile: aqcom
  tags:
    - larpfic
