
# Based on https://github.com/cmprescott/ansible-role-filebot


- name: "Check Filebot Version"
  lineinfile:
    path: "{{ plex_home }}/.ansible_filebot_reg"
    regexp: '^etag'
    line: 'etag {{ filebot_version }}'
    owner: plex
    group: plex
    mode: 0644
    create: yes
  register: FilebotUpdate
  tags:
    - "filebot"

- name: "Setup |  deb | download installer"
  get_url: url="{{ filebot_deb_url }}" dest="{{ filebot_deb_tmp }}"
  when: FilebotUpdate.changed
  tags:
    - "filebot"

- name: "Setup |  deb | run the installer"
  become: Yes
  apt: deb="{{ filebot_deb_tmp }}"
  when: FilebotUpdate.changed
  tags:
    - "filebot"

- name: "Install mediainfo library"
  apt:
   pkg: libmediainfo0v5
   state: present

- name: register licence
  copy:
    src: Filebot_Licence.psm
    dest: "{{ plex_home }}/.filebot_license.psm"
    owner: plex
    group: plex
    mode: 0644
  notify:
    - "register filebot"
  tags:
    - "filebot"