
- name: Remove old iplayer repo
  apt_repository:
    repo: ppa:jon-hedgerows/get-iplayer
    state: absent
  notify:
    - Update APT
  tags:
    - media
    - iplayer


- name: "Check iPlayer Version"
  lineinfile:
    path: "{{ plex_home }}/.ansible_iplayer_reg"
    regexp: '^etag'
    line: 'etag {{ get_iplayer_version }}'
    owner: plex
    group: plex
    mode: 0644
    create: yes
  register: iPlayerUpdate
  tags:
    - media
    - iplayer
    - iplayer_update

- name: "Get iPlayer Script"
  get_url:
    url: "https://raw.githubusercontent.com/get-iplayer/get_iplayer/v{{ get_iplayer_version }}/get_iplayer"
    dest: /usr/local/bin/get_iplayer
    owner: root
    group: root
    mode: 0755
  when: iPlayerUpdate.changed
  tags:
    - media
    - iplayer
    - iplayer_update

- meta: flush_handlers
  tags:
    - media
    - iplayer


- apt:
   pkg:
    - libwww-perl
    - liblwp-protocol-https-perl
    - libmojolicious-perl
    - libxml-libxml-perl
    - libcgi-pm-perl
    - atomicparsley
    - ffmpeg
   state: present
  tags:
    - media
    - iplayer

- name: delete old iplayer script
  file:
    path: "{{ plex_home }}/bin/update_iplayer.sh"
    state: absent

- name: Add update iplayer script to bin
  template: src=download_iplayer.sh dest={{ plex_home }}/bin/download_iplayer.sh mode=0755 owner=plex
  tags:
    - media
    - iplayer


- name: Add download_iplayer cron job
  cron: name="download_iplayer" minute="15" hour=2
        user="plex" job="{{ plex_home }}/bin/download_iplayer.sh >> logger --tag Filebot --server={{ plex_remote_syslog_host }} --port={{ plex_remote_syslog_port }}"
        cron_file=download_iplayer
        state=present
  tags:
    - media
    - iplayer

- name: Make sure plex has a .get_iplayer directory
  file: path={{ plex_home }}/.get_iplayer state=directory owner=plex
  tags:
    - media
    - iplayer

- name: Add iplayer quality config
  lineinfile:
    path: "{{ plex_home }}/.get_iplayer/options"
    regexp: '^tvmode'
    line: tvmode best
    create: yes
  tags:
    - media
    - iplayer

- name: Add subdirformat config
  lineinfile:
    path: "{{ plex_home }}/.get_iplayer/options"
    regexp: '^subdirformat'
    line: subdirformat <nameshort>
    create: yes
  tags:
    - media
    - iplayer

- name: Add subtitles config
  lineinfile:
    path: "{{ plex_home }}/.get_iplayer/options"
    regexp: '^subtitles'
    line: subtitles 1
    create: yes
  tags:
    - media
    - iplayer


- name: Add subdirformat config
  lineinfile:
    path: "{{ plex_home }}/.get_iplayer/options"
    regexp: '^proxy'
    line: "proxy http://{{ nordvpn_username }}:{{ nordvpn_password }}@{{ nordvpn_server }}.nordvpn.com:80"
    create: yes
  tags:
    - media
    - iplayer


- name: Add fileprefix config
  lineinfile:
    path: "{{ plex_home }}/.get_iplayer/options"
    regexp: '^fileprefix'
    line: fileprefix - S<00seriesnum>E<00episodenum>
    create: yes
  tags:
    - media
    - iplayer

- name: Add output config
  lineinfile:
    path: "{{ plex_home }}/.get_iplayer/options"
    regexp: '^output'
    line: output {{ transmission_complete }}/completed/
    create: yes
  tags:
    - media
    - iplayer

- name: Add whitespace config
  lineinfile:
    path: "{{ plex_home }}/.get_iplayer/options"
    regexp: '^whitespace'
    line: whitespace 1
    create: yes
  tags:
    - media
    - iplayer
