---
- name: Remove old iplayer repo
  ansible.builtin.apt_repository:
    repo: ppa:jon-hedgerows/get-iplayer
    state: absent
  notify:
    - Update APT
  tags:
    - media
    - iplayer

- name: Check iPlayer Version
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.ansible_iplayer_reg"
    regexp: ^etag
    line: etag {{ get_iplayer_version }}
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: "0644"
    create: true
  register: iplayer_updated
  tags:
    - media
    - iplayer
    - iplayer_update

- name: Get iPlayer Script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/get-iplayer/get_iplayer/v{{ get_iplayer_version }}/get_iplayer
    dest: /usr/local/bin/get_iplayer
    owner: root
    group: root
    mode: "0755"
  when: iplayer_updated.changed
  tags:
    - media
    - iplayer
    - iplayer_update

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - media
    - iplayer

- name: Install perl modules for iplayer
  ansible.builtin.apt:
    pkg:
      - libwww-perl
      - liblwp-protocol-https-perl
      - libmojolicious-perl
      - libxml-libxml-perl
      - libcgi-pm-perl
      - atomicparsley
      - ffmpeg
    state: present
  tags:
    - media
    - iplayer

- name: Delete old iplayer script
  ansible.builtin.file:
    path: "{{ media_home }}/bin/update_iplayer.sh"
    state: absent

- name: Add update iplayer script to bin
  ansible.builtin.template:
    src: download_iplayer.sh
    dest: "{{ media_home }}/bin/download_iplayer.sh"
    mode: "0755"
    owner: "{{ media_user }}"
  tags:
    - media
    - iplayer

- name: Add download_iplayer cron job
  ansible.builtin.cron:
    name: download_iplayer
    minute: "15"
    hour: 2
    user: "{{ media_user }}"
    job: "{{ media_home }}/bin/download_iplayer.sh | logger --tag Filebot --server={{ medialibrary_remote_syslog_host }} --port={{ medialibrary_remote_syslog_port
      }}"
    cron_file: download_iplayer
    state: present
  tags:
    - media
    - iplayer

- name: Make sure media user has a .get_iplayer directory
  ansible.builtin.file:
    path: "{{ media_home }}/.get_iplayer"
    state: directory
    owner: "{{ media_user }}"
    mode: "0755"
  tags:
    - media
    - iplayer

- name: Add iplayer quality config
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.get_iplayer/options"
    regexp: ^tvmode
    line: tvmode best
    create: true
    mode: "0644"
  tags:
    - media
    - iplayer

- name: Add subdirformat config
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.get_iplayer/options"
    regexp: ^subdirformat
    line: subdirformat <nameshort>
    create: true
    mode: "0644"
  tags:
    - media
    - iplayer

- name: Add subtitles config
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.get_iplayer/options"
    regexp: ^subtitles
    line: subtitles 1
    create: true
    mode: "0644"
  tags:
    - media
    - iplayer

- name: Add subdirformat config
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.get_iplayer/options"
    regexp: ^proxy
    line: proxy http://{{ nordvpn_username }}:{{ nordvpn_password }}@{{ nordvpn_server }}.nordvpn.com:80
    create: true
    mode: "0644"
  tags:
    - media
    - iplayer

- name: Add fileprefix config
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.get_iplayer/options"
    regexp: ^fileprefix
    line: fileprefix - S<00seriesnum>E<00episodenum>
    create: true
    mode: "0644"
  tags:
    - media
    - iplayer

- name: Add output config
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.get_iplayer/options"
    regexp: ^output
    line: output {{ transmission_complete }}/completed/
    create: true
    mode: "0644"
  tags:
    - media
    - iplayer

- name: Add whitespace config
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.get_iplayer/options"
    regexp: ^whitespace
    line: whitespace 1
    create: true
    mode: "0644"
  tags:
    - media
    - iplayer
