---
# Script support
- name: Make sure media library has a bin
  ansible.builtin.file:
    path: "{{ media_home }}/bin"
    state: directory
    owner: "{{ media_user }}"
    mode: "0755"
  tags:
    - media

- name: Install filebot
  ansible.builtin.include_tasks: filebot.yml
  tags:
    - media
    - filebot

- name: Install get_iplayer
  ansible.builtin.include_tasks: iplayer.yml
  tags:
    - media

- name: Disable protected hardlinks (makes filebot hardlink work)
  ansible.builtin.lineinfile:
    line: fs.protected_hardlinks = 0
    state: present
    dest: /etc/sysctl.conf
  notify: Kick sysctl
  tags:
    - media
# Sync non-TV shows to their own libraries

- name: Add sync_or_swim script to bin
  ansible.builtin.debug:
    msg: "{{ media_home }}/bin/sync_or_swim.sh"
  tags:
    - media
    - sortitaaht

- name: Add sync_or_swim script to bin
  ansible.builtin.template:
    src: sync_or_swim.sh
    dest: "{{ media_home }}/bin/sync_or_swim.sh"
    mode: "0755"
    owner: "{{ media_user }}"
  tags:
    - media
    - sortitaaht

# Sort It Ahht

- name: Add sortitaaht script to bin
  ansible.builtin.template:
    src: sortitaaht.sh
    dest: "{{ media_home }}/bin/sortitaaht.sh"
    mode: "0755"
    owner: "{{ media_user }}"
  tags:
    - media

- name: Add verbose sortitaaht script to bin
  ansible.builtin.template:
    src: sortitaaht.sh
    dest: "{{ media_home }}/bin/sortitaaht_verbose.sh"
    mode: "0755"
    owner: "{{ media_user }}"
  tags:
    - media
  vars:
    verbose: true

- name: Add Clear Bullshit script to bin
  ansible.builtin.template:
    src: clear_bullshit.sh
    dest: "{{ media_home }}/bin/clear_bullshit.sh"
    mode: "0755"
    owner: "{{ media_user }}"
  tags:
    - media

- name: Add sortitaaht cron job
  ansible.builtin.cron:
    name: filebot
    minute: 2,32
    user: "{{ media_user }}"
    job: "{{ media_home }}/bin/sortitaaht.sh 2>&1 | logger --tag Filebot --server={{ medialibrary_remote_syslog_host }} --port={{ medialibrary_remote_syslog_port }}"
    cron_file: filebot
    state: present
  tags:
    - media

- name: Delete old youtube script
  ansible.builtin.file:
    path: "{{ media_home }}/bin/youtube_download.sh"
    state: absent
  tags:
    - media
    - dlyoutube

- name: Add download_youtube script to bin
  ansible.builtin.template:
    src: download_youtube.sh
    dest: "{{ media_home }}/bin/download_youtube.sh"
    mode: "0755"
    owner: "{{ media_user }}"
  tags:
    - media
    - media_playlists
    - dlyoutube

- name: Add download_youtube cron job
  ansible.builtin.cron:
    name: download_youtube
    minute: "15"
    hour: 3
    user: "{{ media_user }}"
    job: "{{ media_home }}/bin/download_youtube.sh 2>&1  | logger --server={{ medialibrary_remote_syslog_host }} --port={{ medialibrary_remote_syslog_port }} --tag youtube"
    cron_file: download_youtube
    state: present
  tags:
    - media
    - dlyoutube

- name: Install Transmission & Aria
  ansible.builtin.apt:
    state: present
    pkg:
      - transmission-cli
      - aria2
  tags:
    - media
    - dlyoutube

- name: Add remove_completed_torrents script to bin
  ansible.builtin.template:
    src: remove_completed_torrents.sh
    dest: "{{ media_home }}/bin/remove_completed_torrents.sh"
    mode: "0755"
    owner: "{{ media_user }}"
  tags:
    - media

- name: Add remove_completed_torrents cron job
  ansible.builtin.cron:
    name: remove_completed_torrents
    minute: "15"
    hour: 18
    user: "{{ media_user }}"
    job: "{{ media_home }}/bin/remove_completed_torrents.sh 2>&1 | logger --server={{ medialibrary_remote_syslog_host }} --port={{ medialibrary_remote_syslog_port }} --tag torrent_remove"
    cron_file: remove_completed_torrents
    state: present
  tags:
    - media

- name: Add media logrotate
  ansible.builtin.template:
    src: media_logrotate.j2
    dest: /etc/logrotate.d/media_logrotate
    mode: "0644"
    owner: root
  tags:
    - logrotate
