---
# defaults file for roles/firth_alchemistic

firth_alchemistic_image: ghcr.io/istic/alchemistic
firth_alchemistic_image_tag: latest

firth_alchemistic_app_url:
firth_alchemistic_app_key:
firth_alchemistic_db_host: host.docker.internal
firth_alchemistic_db_port: 3306
firth_alchemistic_db_name:
firth_alchemistic_db_user:
firth_alchemistic_db_password:
firth_alchemistic_mail_host:
firth_alchemistic_mail_port: 587
firth_alchemistic_mail_username:
firth_alchemistic_mail_password:
firth_alchemistic_mail_from_address:
firth_alchemistic_mail_from_name: Alchemistic

# Port exposed to localhost for the upstream nginx fastcgi_pass
firth_alchemistic_fpm_port: 9000

# Shared Docker network name (must match firth_sftp_docker role)
# firth_services_network: firth_services
