name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    working-directory: ansible

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        vault_password: ${{ secrets.VaultPassword }}
        targets: |
            "playbook.yml"
        override-deps: |
          ansible==2.8
          ansible-lint==4.2.0
