---
name: Ansible Lint # feel free to pick your own name

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.VaultPassword }}
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4
        # We drop the ansible.cfg file to unset the vault_password_file option
      - name: Drop ansible.cfg file
        run: rm ansible.cfg
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@v6
