---
name: Ansible Lint # feel free to pick your own name

true: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.VaultPassword }}
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3

      - name: Lint Ansible Playbook
        uses: ansible-community/ansible-lint-action@main
