name: auto-merge

on:
  pull_request:
permissions: read-all
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      checks: write
      actions: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Automerge DependaBot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
