---
- name: Safe Upgrade
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 21600
    upgrade: safe
    autoremove: true
  tags:
    - patch

- name: Safe Remove
  ansible.builtin.apt:
    autoremove: true
  tags:
    - patch
