---
- name: Safe Upgrade
  ansible.builtin.apt: update_cache=yes cache_valid_time=21600 upgrade=safe autoremove=yes
  tags:
    - patch

- name: Safe Remove
  ansible.builtin.apt: autoremove=yes
  tags:
    - patch
