- name: AWS Config - Aqcom - Region
  community.general.ini_file:
    path: ~/.aws/config
    section: profile aqcom
    option: region
    value: "{{ aqcom_aws_default_region }}"
    mode: '0600'
    backup: true
  tags:
    - aws

- name: AWS Creds - Aqcom - Key
  community.general.ini_file:
    path: ~/.aws/credentials
    section: aqcom
    option: aws_access_key_id
    value: "{{ aqcom_aws_key }}"
    mode: '0600'
    backup: true
  tags:
    - aws

- name: AWS Creds - Aqcom - Secret
  community.general.ini_file:
    path: ~/.aws/credentials
    section: aqcom
    option: aws_secret_access_key
    value: "{{ aqcom_aws_secret }}"
    mode: '0600'
    backup: true
  tags:
    - aws


- name: AWS Config - Istic - Region
  community.general.ini_file:
    path: ~/.aws/config
    section: profile istic
    option: region
    value: "{{ aqcom_aws_default_region }}"
    mode: '0600'
    backup: true
  tags:
    - aws

- name: AWS Creds - istic - Key
  community.general.ini_file:
    path: ~/.aws/credentials
    section: istic
    option: aws_access_key_id
    value: "{{ istic_aws_key }}"
    mode: '0600'
    backup: true
  tags:
    - aws

- name: AWS Creds - istic - Secret
  community.general.ini_file:
    path: ~/.aws/credentials
    section: istic
    option: aws_secret_access_key
    value: "{{ istic_aws_secret }}"
    mode: '0600'
    backup: true
  tags:
    - aws
